[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "python3.11 -m pip install --upgrade pip setuptools wheel",
    "python3.11 -m pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python3.11 -m uvicorn app:app --host 0.0.0.0 --port $PORT"
